source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

def firestack_pods
[
  'Firebase/Core',
  'Firebase/Auth',
  'Firebase/Storage',
  'Firebase/Database',
  'Firebase/RemoteConfig',
  'Firebase/Messaging'
].each do |lib|
  pod lib
end

target 'firestack' do
  firestack_pods
end

# target 'firestack' do
# end